### ISSUE TITLE
exwm layer can't be found

### ISSUE THREAD

**Issue by moritzschaefer** [timor/spacemacsOS#1]
I'm using spacemacs from the master-branch. When adding exwm to dotspacemacs-configuration-layers and reloading the confing (SPC feR) I get an error that exwm can't be found.

**Comment by Gavus** [comment]
You can place the repository in ~/.emacs.d/private/local/exwm or ~/.spacemacs.d/layers/exwm. Both worked for me.

**Comment by Aberrantfox** [comment]
Yea worth noting... it means to put the contents of the repository into the path `~/.emacs.d/private/local/exwm`. Don't cd into that directory and git clone there like I did. Hopefully, this comment will save someone as stupid as me a few minutes in the future.

**Comment by moritzschaefer** [comment]
You can clone and rename spacemacsOS to exwm or directly

`git clone https://github.com/timor/spacemacsOS/ exwm`
