### ISSUE TITLE
Feature request: Make s-SPC s-SPC invoke s-SPC SPC or M-x as standard behavior

### ISSUE THREAD

**Issue by nhmacuk** [timor/spacemacsOS#10]
After mistyping this many times, I wonder if this should be standard behavior. What do you think?
I noticed how useful s-SPC really is, since I don't have to think whether I am in normal or insert mode.

**Comment by timor** [comment]
Thanks for pointing this out.  Should be working now.

**Comment by nhmacuk** [comment]
Just pulled the new version, but doesn't seem to be working yet: pressing <s-SPC>  <s-SPC> results in: 
s-SPC-  which-key: There are no keys to show [2 times]
*After 0 kbd macro iterations: undefined: Keyboard macro terminated by a command ringing the bell*
By the way do you know how I could be able to see the which-key for the s-SPC prefix?
