### ISSUE TITLE
Beginner Problem with exwm

### ISSUE THREAD

**Issue by comcloudway** [timor/spacemacsOS#13]
I'm pretty new to emacs, learning more as I go.
After installing spacemacsOS according to the installation guide I restarted emacs to install missing packages and then restarted it again and now it is throwing this error:

Error (use-package): exwm/:config: Symbol’s function definition is void: configuration-layer/layer-used-p

I tried googling it put nothing relevant turned up.
I reinstalled spacemacsOS and the Error message is still there

EDIT: I'm running emacs-26.3 and the latest available version from the spacemacs website in Arch Linux

**Comment by timor** [comment]
This is probably not caused by a general mistake in your setup.

Someone reported the same thing after 83b97b238bd7025a2829df8d6e51ad00e6d2caef.
I'm not really sure why that is, as other layers also seem to use that function
in their `package.el` file without any declaration or `require`...

Sometimes these issues are related to stale `.elc` files from a weird state of the byte-compiler.  Do you have a `core/core-configuration-layer.elc` file in your Spacemacs checkout, any `.elc` file in your exwm layer subdirectory?

**Comment by comcloudway** [comment]
In my .emcs.d/core directory is only a core/core-configuration-layer.el as find returned
`$find core/core-configuration-layer.el`
`core/core-configuration-layer.el`
but there is no *.elc file in my emacs directory
`find .elc`
`find: ‘.elc’: No such file or directory`

I'm not shure whether this might be related to my second problem:
It seems like the `exwm//install-frame-keybindings` is never called - at least I assume, because there is no F keybinding 
`s-SPC` only lists f-files and then h - help

**Comment by timor** [comment]
I don't know whether that was just a typo, but if you are using GNU `find` to search for `.elc` files, you'd need to run

```
find ~/.emacs.d/core -name '*.elc'
find ~/.emacs.d/private -name '*.elc'
```

provided that your Spacemacs and private layers are installed in `~/.emacs.d`.

Anyways, can you give me the exact Spacemacs version you are running?

**Comment by timor** [comment]
> EDIT: I'm running emacs-26.3 and the latest available version from the spacemacs website in Arch Linux

Oh, I missed that part in the description.  If you just follow the instructions on https://wiki.archlinux.org/index.php/Spacemacs, you will probably end up with the `master` branch of Spacemacs.

```
$ git branch --show-current
master
```

The `master` branch is very old at the moment.  I'm quite certain you will have to switch to the `develop` branch to run spacemacsOS.

**Comment by comcloudway** [comment]
Still trying to install the latest version from github, but git clone keeps failing - will keep you posted

**Comment by comcloudway** [comment]
Finally had time to update emacs to version 28.0.50, but the problem is not solved for me, and the SPC-F shortcut still seems to be missing, will do further testing later

EDIT: Just noticed that I misread your message and updated emacs instead of spacemacs.

**Comment by comcloudway** [comment]
Ok, getting back to you now as I finally had time to do some more work on my spacemacs config.
I've switched to the development branch, as the ReadME for this Project suggests and now `git branch --show-current` returns default but the problem still exists.
I've tried reinstalling emacs, spacemacs and spacemacsOS multiple times but it doesn't seem to fix it

**Comment by comcloudway** [comment]
Hey!
I've finally made it 
Reinstalled spacemacs and directly cloned the development branch and installed spacemacsOS in .emacs.d/private/local/exwm.
And now it is working and neither showing the warning messaging nor not giving me the s-SPC-F option.
Thanks for the work you put in to help me.
Only one question, from using bspwm I'm used to going SUPER-[1-9] to switch  to that workspace even if there is nothing on  in, but in exwm it doesn't behave like this? when using SUPER-2 to switch workspace it says: [EXWM] Workspace index out of range:1 - not sure whether this is related to this repo or exwm directly

**Comment by timor** [comment]
`s-1` - `s-9` are bound to `exwm-workspace-switch` by the layer.  The behavior you want should be possible if you rebind these keys to `exwm-workspace-switch-create`.

**Comment by comcloudway** [comment]
Thanks.
Closing the issue now as my problems are resolved
EDIT: changed keybindings to exwm-workspace-switch-create and it worked nearly flawlessly, but I've noticed that I personally seem to find it easier to organise my workspaces with exwm-workspace-switch as I dont have that many created workspaces I can put stuff on - definitly learned something
