### ISSUE TITLE
void-function:(dbus-call-method)

### ISSUE THREAD

**Issue by HakunanMatatat** [timor/spacemacsOS#14]
hi,I installed exwm through https://github.com/timor/spacemacsOS. An error occur:

> Warning (emacs) :[EXWM] EXWM fails to start (void-function:(dbus-call-method))

What's wrong with it?Thank you very much.

**Comment by lialzm** [comment]
me too , but in spacemacs master branch is ok

**Comment by timor** [comment]
> > Warning (emacs) :[EXWM] EXWM fails to start (void-function:(dbus-call-method))
> 
> What's wrong with it?Thank you very much.

That is hard to tell without further details.  Which version of emacs are you using? Which version of spacemacs are you using?

**Comment by HakunanMatatat** [comment]
emacs27 + the  up-to-date develop branch

**Comment by OZoneGuy** [comment]
I am getting the same error, and I am also updated. Is there something we can do to provide more info. Would really like to use this.

**Comment by OZoneGuy** [comment]
@HakunanMatatat  So I found a pseudo solution. Just try looking up the definition of the function...
 All the functions are registered in spacemacs, but for some reason they are not loaded immediately.
After getting the error, I just used `descripe-function` and looked up the void functions. And it worked! It is rather weird.

**Comment by brioglade** [comment]
@OZoneGuy  The warning is still there when I typed "C-h f dbus-call-method".

**Comment by timor** [comment]
Sorry, I haven't had the chance to try this out with emacs-27 yet.  Maybe something changed about the load order and I am missing a `require` or something...

Does adding `(require 'dbus)` at the top of `funcs.el` change anything?

**Comment by timor** [comment]
This is not an emacs-27 issue. I simply forgot a require in `funcs.el`, but that was shadowed by my dotfile.  Should be fixed in
2f77bf1f4c13786a8d1274d7a7c10b36c216954c.
