### ISSUE TITLE
spacemacsWM instead of spacemacsOS

### ISSUE THREAD

**Issue by Gavus** [timor/spacemacsOS#3]
Have you  consider using spacemacsWM instead of spacemacsOS? I think its confusing to use OS as the layer does not contribute for Emacs OS wise. Wouldn't spacemacsWM be more suitable? Or perhaps spacemacs-EXWM as it is in my understanding  an exwm layer.

**Comment by timor** [comment]
The name spacemacsOS was already there when I forked it.  Most of the code and ReadMe are not created by me, so I did not consider it
