### ISSUE TITLE
wrong type argument commandp

### ISSUE THREAD

**Issue by demokritos** [timor/spacemacsOS#5]
https://github.com/timor/spacemacsOS/blob/ece8ffb60e51c677e76f2ffe2fc6b83b51bb1760/funcs.el#L16

This code results in error 'wrong type argument commandp' since `exwm-input--grab-keyboard` is not an interactive function. I think it should be replaced with `exwm-input-grab-keyboard`.

**Comment by timor** [comment]
While I agree that the code should fail, for some reason I don't trigger that error.

Can you provide reproduction steps and maybe a backtrace?

**Comment by demokritos** [comment]
This layer doesn't fail. Just when I call this function other places, I get this error.
I am sorry I didn't seem to be clear.

**Comment by timor** [comment]
For some reason that code path does not seem to be traversed at the moment, although the advice in which it is used is actually created.
