### ISSUE TITLE
back to login window on Ubuntu 18.04

### ISSUE THREAD

**Issue by csfreebird** [timor/spacemacsOS#8]
I am using Ubuntu 18.04, follow your document, just one thing changed,
put the exwm.desktop file into /usr/share/xsessions instead of /usr/local/xsessions folder.
Now I  logout and select EXWM session and login, I can see the *spacemacs* buffer, but after a while, it closed and get back to ubuntu login window.
Where can I find some logs to dig into the reason?

**Comment by timor** [comment]
Unfortunately I don't have a Ubuntu system to try that out on.  Is there some way in Ubuntu to start spacemacs from your `~/.xsession`, to see if that works?

I used to debug stuff like this by logging into an X session which only starts an xterm, and then starting the window manager by hand.

**Comment by timor** [comment]
@csfreebird Do you have any more information on this by now?  Otherwise I would close this for now, as I can't really do anything about it.
