### ISSUE TITLE
What would your recommended way be to issue a shell command before initialisation?

### ISSUE THREAD

**Issue by nhmacuk** [timor/spacemacsOS#9]
I would like to issue the commands ```unlcutter &``` and your ```setxkbmap -option 'ctrl:no caps'```. The latter doesn't seem to work using only your (very nice) package. Maybe my setup doesn't recognize your exwm-start file? Should I delete any existing .xinitrc and desktop files that are located elsewhere? My desktop file in /usr/share/xsessions/ reads:  
```
[Desktop Entry]
Name=EmacsWM
Comment=Emacs Window Manager
Exec=emacs
Type=Application
```
I want to prevent editing the files in your package directly so I can easily update them. 
Do I correctly apply the example from the README file in the following way:
```
     (exwm :variables
           ;; exwm-terminal-command "unlcutter &"
           exwm-custom-init (lambda() (exwm/autostart-process "unclutter &" "setxkbmap -option 'ctrl:no caps'")))
```

**Comment by timor** [comment]
Could you describe what exactly does not work?

**Comment by nhmacuk** [comment]
My issue consists of my understanding of the exwm-start file, and how to best configure your program.
The behavior I would like to see is that caps lock is remapped to left control as I expect from the exwm-start file, and that exwm/emacs/my system activates a command when starting up an emacs session (in this case unclutter).
The former behavior I expected because of the line ```setxkbmap -option 'ctrl:no caps'``` in the exwm-start file from your package. 
The latter I want to start myself by for example adding it to exwm-start. However as the former doesn't work I wonder how exwm-start is used by my setup, as all described in your README works great. Moreover, I thought it would be better to prevent modifying your package directly to maintain it more easily. 
I attempted to configure the package to these needs using the example in the README. But the elisp that I inserted into my earlier message caused exwm to not start. 
Sorry for the unclear message.

**Comment by timor** [comment]
What  linux distribution are you using?  Are you using a display manager to log in?

Also, the desktop file snippet above only starts `emacs`.  The bundled example file calls the `exwm-start` helper script in the `Exec=` line.

The bundled files are really examples.  Don't hesitate to write your own, they are not universal.

Note that in the `.spacemacs` snippet, your call to `exwm/autostart-process` is missing the name of the process as the first argument (which you can freely choose).

**Comment by nhmacuk** [comment]
The issue is resolved; I changed the elisp like you recommended, and removed the "&" after my command. I am confident that I could get the other command from your example working too now. 
(My distribution is Manjaro XFCE. I log into a session (which I think is a diplay manager) where EXWM starts up immediately and does not replace the XFCE window manager. 
I really like your configurations, so I try to update regularly to benefit from the new features, and don't edit much to keep merging simple. I hope it will be an official layer soon.)
Thank you!
